transPACT: KS specificity prediction for transAT PKSs
antismash/antismash pull request #306
Opened 2020-10-19 17:37 UTC by chevrm

Still todo:

- Better testing for all functions
- Only fire transpact module when transAT KS (right now, fires for all KSs)

2020-10-19 17:40 UTC, SJShaw commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 38
           

Complexity increasing per file
==============================
- antismash/modules/nrps_pks/substrates.py  1
- antismash/modules/nrps_pks/transat_ks_analysis/transat_ks_analysis.py  9
- antismash/common/subprocessing/pplacer.py  6
- antismash/modules/nrps_pks/transat_ks_analysis/test/test_transat_ks_analysis.py  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/antismash/antismash/pullRequest?prid=6364651&bid=20656507)

2020-11-02 08:36 UTC, SJShaw requested changes
I know you're still working on this, I just thought I'd poitn out a few things before I forget to mention them at all.

2020-11-02 08:36 UTC, SJShaw commented on antismash/config/executables.py
> +## NOTE: not sure if this is the right place for this, but this was necessary on my box for pplacer and guppy to run correctly
This isn't necessary on a Debian system with the usual `LANG` environment variables, this is a bit of a nuclear approach to what is really a per-system setting. 

I don't think it should be included at all, but if absolutely necessary it should be limited in scope to the actual guppy/pplacer executions.

2020-11-02 08:36 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/data/RAxML_bestTree.649KS_sequences_hmmalign_raxml_renamed.refpkg/RAxML_info.649KS_sequences_hmmalign_raxml.tre
> +
These data files have some pretty obnoxius paths. If it's long to include all the relevant info, that should be in a generation script included with the files so we can regenerate them consistently at some point in the future (and the pre-processed data, if it's small, maybe should be included, or if it's not small, have information on where to get it).

2020-11-02 08:36 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/data/RAxML_bestTree.649KS_sequences_hmmalign_raxml_renamed.refpkg/RAxML_info.649KS_sequences_hmmalign_raxml.tre
> +Normally they should be excluded from the analysis.
This warning suggests that the pre-processed data could be cleaned up a bit.

2020-11-02 08:36 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/test/test_transat_ks_analysis.py
> +        results = run_transpact_ks_analysis(query_ks)
This function is undefined at this point, so nothing is being tested at all.

Also, unit tests shouldn't be executing external programs, we have nearly 900 unit tests that run in less than 6 seconds on my laptop, but this single line adds one test that takes 25 seconds alone. Either mock the output of the external commands or move it to an integration test (by changing the filename from `test_*` to `integration_*` and running with `make integration` instead).

2020-12-16 10:14 UTC, SJShaw requested changes
There might be more issues that crop up when I get to running this over a good variety of inputs, but there's enough to change already that I think that step can wait for the next iteration.

I can do some of the cleanup, if you're happy to wait for a bit, but there's some parts still need explanation.

2020-12-16 10:14 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/transat_ks_analysis.py
> +            query_prefix = re.sub(r"^(.+)_#\d+_M=\d+?\.?\d*$", "\g<1>", tree_hits[placement_num].name)
`query_prefix` doesn't seem to be used for anything.

2020-12-16 10:14 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/transat_ks_analysis.py
> +        mass = float(re.sub(r"^.+#\d+_M=(\d+?\.?\d*)$", "\g<1>", tree_hits[placement_num].name))
Rather than a regex, why not just use `mass = float(tree.hits[placement_num].name.rsplit("M=", 1)[1])`?

2020-12-16 10:14 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/transat_ks_analysis.py
> +            placementn = re.sub(r"^#(\d+)$", "\g<1>", ln[-2]) ## placement number, zero indexed
This is a much more complicated version of `ln[-2][1:]`, by the look of it.

2020-12-16 15:08 UTC, chevrm commented on antismash/modules/nrps_pks/substrates_pks.py
> +    return bool(has_ks and not has_at)
removed all bools

2020-12-16 15:12 UTC, chevrm commented on antismash/modules/nrps_pks/substrates_pks.py
> +            if domain.name in ["PKS_AT", "CAL_domain", "PKS_KR", "PKS_KS"]:
left over from previous implementation. no longer necessary so I've put it back the way it was

2020-12-16 17:39 UTC, chevrm commented
All listed issues addressed in about 20 minutes. Confirmed that output is unchanged and still looks good, all automatic tests pass.

2020-12-21 15:08 UTC, SJShaw commented
I've played around with it a little, and I think there's going to need to be some kind of explanatory text to go along with the predictions, since they're not nearly as recognisable as the previous NRPS/PKS predictions which are all standard amino acids.

I think the best method might be to use the same method as used for the protocluster products, which link to the documentation site. This will help avoid us getting lots of questions like "What's the difference between `b_L_OH` and `b_LOH`?" or "Why does it sometimes predict 

What might complicate that approach is the possible predictions. That linking system requires an HTML-compatible element ID to use in the link, and the predictions don't allow for that right now. There's quite a few with `/`, which I'm assuming is separating different possibilities, and would need multiple links if they're intended to be multiple options (as a side note, we can't build on those easily with a module monomer alteration system at all, which is why we added restrictions on those to the NRPS predictions). There's some others with parentheses that I don't know whether they're adding extra information or just weren't consistently added (`b_OH/eDB` and `b_OH/eDB(enacyloxins)`).

There's also what looks to be few inconsistencies that will trip up an anchor based linking system, since we can't add multiple IDs to an element on the docs site:
- `nnon_elongating_DB_before_branching` vs non_elongating_DB_before_branching`
- `aromatic starter` vs `aromatic_Starter` (case matters in the link)
- `amino acids` vs `amino_acids`
- `aMe_red/bOH/bketo` and `aMe_reduced`, if we go with the multiple links route
- `aOH_bOH` vs `mostly_a_OH_b_OH`

There's also a couple of predictions that we don't gain anything from listing as a prediction (`unknown` and `various`), especially since it conflicts with the `NA` when no prediction is made at all. It's fine to have them in the tree to improve the other prediction accuracy, but perhaps should be filtered out and treated as a non-prediction. If they really should be present as they're meaningful, then a more meaningful name is needed.


We probably also need to add some other kind of output, since I don't think most people will even notice the results are present. A sidepanel separate to the existing `NRPS/PKS monomers` might be the best bet there.

If you've got any alternative ideas about how to communicate the results to the user, I'm all ears.

2020-12-21 15:09 UTC, SJShaw commented on antismash/modules/nrps_pks/transat_ks_analysis/transat_ks_analysis.py
> +            " <dt>transPACT assigned specificiy:</dt>\n"
There's a typo here: `specificicy`

2021-02-03 06:03 UTC, chevrm commented
> I've played around with it a little, and I think there's going to need to be some kind of explanatory text to go along with the predictions, since they're not nearly as recognisable as the previous NRPS/PKS predictions which are all standard amino acids.
> 
> I think the best method might be to use the same method as used for the protocluster products, which link to the documentation site. This will help avoid us getting lots of questions like "What's the difference between `b_L_OH` and `b_LOH`?" or "Why does it sometimes predict
> 
> What might complicate that approach is the possible predictions. That linking system requires an HTML-compatible element ID to use in the link, and the predictions don't allow for that right now. There's quite a few with `/`, which I'm assuming is separating different possibilities, and would need multiple links if they're intended to be multiple options (as a side note, we can't build on those easily with a module monomer alteration system at all, which is why we added restrictions on those to the NRPS predictions). There's some others with parentheses that I don't know whether they're adding extra information or just weren't consistently added (`b_OH/eDB` and `b_OH/eDB(enacyloxins)`).
> 
> There's also what looks to be few inconsistencies that will trip up an anchor based linking system, since we can't add multiple IDs to an element on the docs site:
> 
>     * `nnon_elongating_DB_before_branching` vs non_elongating_DB_before_branching`
> 
>     * `aromatic starter` vs `aromatic_Starter` (case matters in the link)
> 
>     * `amino acids` vs `amino_acids`
> 
>     * `aMe_red/bOH/bketo` and `aMe_reduced`, if we go with the multiple links route
> 
>     * `aOH_bOH` vs `mostly_a_OH_b_OH`
> 
> 
> There's also a couple of predictions that we don't gain anything from listing as a prediction (`unknown` and `various`), especially since it conflicts with the `NA` when no prediction is made at all. It's fine to have them in the tree to improve the other prediction accuracy, but perhaps should be filtered out and treated as a non-prediction. If they really should be present as they're meaningful, then a more meaningful name is needed.
> 
> We probably also need to add some other kind of output, since I don't think most people will even notice the results are present. A sidepanel separate to the existing `NRPS/PKS monomers` might be the best bet there.
> 
> If you've got any alternative ideas about how to communicate the results to the user, I'm all ears.

The unit of prediction is the clade. What is reported to the user is the annotation of a clade, which is just a column in the lookup dictionary. It's just a matter of changing the flat file to whatever you think is best.

2021-02-05 17:28 UTC, chevrm commented
Annotations have been updated. Please review.

2021-02-08 09:09 UTC, SJShaw commented
There's no real point reviewing the code when it can't complete a run.

Please run the tests (even the unit tests, which caught this) and run on a relevant input to check the output before pushing, it'll save everyone some time.

2021-02-08 15:57 UTC, chevrm commented
All checks passed.

2021-02-08 15:57 UTC, chevrm commented
All checks passed.

2021-02-08 16:00 UTC, chevrm commented
Checks passed.

2021-02-08 16:00 UTC, chevrm commented
Checks passed.

2021-02-08 17:32 UTC, SJShaw commented
> There's also a couple of predictions that we don't gain anything from listing as a prediction (unknown and various), especially since it conflicts with the NA when no prediction is made at all. It's fine to have them in the tree to improve the other prediction accuracy, but perhaps should be filtered out and treated as a non-prediction. If they really should be present as they're meaningful, then a more meaningful name is needed.

This is still an issue.

> We probably also need to add some other kind of output, since I don't think most people will even notice the results are present. A sidepanel separate to the existing NRPS/PKS monomers might be the best bet there.

This is also still an issue.

2021-02-08 20:22 UTC, chevrm commented
All "non-call" specialties are now reported as "clade_not_conserved". This includes those previously listed as NA, Unknown, Various, etc.

A simple output into the NRPS/PKS monomers tab is now working. I have very little html experience, so if further editing of that is needed I don't think I'll be much help.

2022-11-22 15:06 UTC, SJShaw commented
I'm closing this PR as #474 supersedes it.

2022-11-22 15:06 UTC, closed without merging