Style pass
antismash/antismash pull request #543
Opened 2023-02-10 12:50 UTC by SJShaw

Fixes the majority of style issues found via pylint and flake8 that aren't variants of `too-many-*`. 

Some style messages were common enough to justify a single commit for that specific type.

2023-02-17 21:11 UTC, kblin requested changes
I think cleaning up the lasso and thiopeptide lists like the lanthipeptide and sactipeptide modules would be nice, otherwise I think it's good to go.

2023-02-20 12:19 UTC, SJShaw commented on antismash/modules/lassopeptides/specific_analysis.py
> -    columns.append(sum([charge_dict[aa] for aa in core if aa in charge_dict]))
Done

2023-02-20 12:20 UTC, SJShaw commented on antismash/modules/thiopeptides/rodeo.py
> -    columns.append(sum([leader.count(aa) for aa in "FWY"]))
Done

2023-02-20 13:12 UTC, kblin commented on antismash/common/layers.py
> -                current_id += " (original name was: %s...)" % orig_id[:60]
Scheduled for a future PR

2023-02-20 13:14 UTC, kblin approved these changes
Looks good to me 👍

2023-02-20 13:14 UTC, merged